name: check_install_script
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron : '0 0 * * *' # Every midnight check the released version of default branch
  

jobs:
  install-macos:
    name: install-macos
    runs-on: macos-latest
    steps:
      - name: test_install_on_macos
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"

          # Test install succeeeded 
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/clang/*/bin/clang
          test -f ~/.tipi/cmake/*/bin/cmake
          test -f ~/.tipi/emsdk/*/emsdk
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/go/*/bin/go
          test -f ~/.tipi/jdk/*/Contents/Home/bin/jar
          test -f ~/.tipi/nodejs/*/bin/node
          test -f ~/.tipi/openapi/*/openapi-generator-cli-5.1.1.jar
          test -f ~/.tipi/openapi-generator-script/*/openapi-generator-cli
          test -f ~/.tipi/platform/*/cmake/projects/Poco/hunter.cmake
          test -f ~/.tipi/python/*/bin/python
          test -f ~/.tipi/file-sync/*/pysearpc/client.py

  install-linux:
    name: install-linux
    runs-on: ubuntu-latest
    steps:
      - name: test_install_on_linux
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          echo "Script source : ${script_source}"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
          
          # Test install succeeeded 
          echo "verif tipi"
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/clang/*/bin/clang
          test -f ~/.tipi/cmake/*/bin/cmake
          test -f ~/.tipi/emsdk/*/emsdk
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/go/*/bin/go
          test -f ~/.tipi/jdk/*/bin/jar
          test -f ~/.tipi/nodejs/*/bin/node
          test -f ~/.tipi/openapi/*/openapi-generator-cli-5.1.1.jar
          test -f ~/.tipi/openapi-generator-script/*/openapi-generator-cli
          test -f ~/.tipi/file-sync/*/pysearpc/client.py
          test -f ~/.tipi/platform/*/cmake/projects/Poco/hunter.cmake

  install-windows-powershell:
    name: install-windows-powershell
    runs-on: windows-latest
    steps:
      - name: test_install_on_windows_powershell
        run: |
          if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
            $script_source = $env:GITHUB_HEAD_REF.replace('refs/heads/', '')
          } else {
            $script_source = $env:GITHUB_REF.replace('refs/heads/', '')
          }
          . { iwr -useb https://raw.githubusercontent.com/tipi-build/cli/$script_source/install/install_for_windows.ps1 } | iex 
          if (!($?)) {exit 1}
          # Test install succeeeded 
          if (!(Test-Path "C:\\ProgramData\\tipi\\tipi.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\clang\\4ee08f2e332b2080663072d5a6ce0200508a83e4\\bin\\clang.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\cmake\\51e611bb39f8f4c49a160085048e0dd24ec22812\\bin\\cmake.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\emsdk\\f693e7f511d2d320d20a1376812321763027728e\\emsdk.bat" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\environments\\690be18d90ea5d264c93cea5a372dcaab64fd33d\\xcode.cmake" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\go\\782c595c1aece9fea8bfa7a14bfbf52e206a0f91\\bin\\go.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\jdk\\112dbf189260a647842e98671516f18e4de070f9\\bin\\jar.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\nodejs\\ec44ef72df91ffc4b02df49e75c46b8f845fab5e\\node.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\openapi\\ec7cbaed034d7aaeb2a0f22619a8927c08a74894\\openapi-generator-cli-5.1.1.jar" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\openapi-generator-script\\4fc850d4a145be49a9aa0428dcbc5c5c82f19f93\\openapi-generator-cli.bat" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\openssh\\0a60a7d9d6ac67dfe4b97f720ad780dd185ed432\\ssh.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\perl\\ac3ce102081ac6f9b3b43d81c30ac77b08493eff\\README.txt" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\platform\\2a344bab73de81f19feca4fa3d724e1d9607d55e\\cmake\\projects\\Poco\\hunter.cmake" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\python\\30314b4574f1f162767a6a66a64410b9a9e2829d\\python.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\file-sync\\01b125c46bed19ec725984b91aa8ac096ec3c7f2\\pysearpc\\client.py" -PathType leaf)) { exit 1; }
        shell: powershell 

  install-archlinux:
    name: install-archlinux
    runs-on: ubuntu-latest
    env:
      GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
      GITHUB_HEAD_REF: $GITHUB_HEAD_REF
      GITHUB_REF: $GITHUB_REF
    container: 
      image: archlinux
    steps:
      - name: test_install_on_linux
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          echo "Script source : ${script_source}"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
          # Test install succeeeded 
          echo "verif tipi"
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/clang/*/bin/clang
          test -f ~/.tipi/cmake/*/bin/cmake
          test -f ~/.tipi/emsdk/*/emsdk
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/go/*/bin/go
          test -f ~/.tipi/jdk/*/bin/jar
          test -f ~/.tipi/nodejs/*/bin/node
          test -f ~/.tipi/openapi/*/openapi-generator-cli-5.1.1.jar
          test -f ~/.tipi/openapi-generator-script/*/openapi-generator-cli
          test -f ~/.tipi/file-sync/*/pysearpc/client.py
          test -f ~/.tipi/platform/*/cmake/projects/Poco/hunter.cmake

