name: check_install_script
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron : '0 0 * * *' # Every midnight check the released version of default branch
  

jobs:
  install-macos-full:
    name: install-macos-full
    runs-on: macos-latest
    steps:
      - name: test_install_on_macos
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          export TIPI_DISTRO_MODE=all
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"

          # Test install succeeeded 
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/clang/*/bin/clang
          test -f ~/.tipi/cmake/*/bin/cmake
          test -f ~/.tipi/emsdk/*/emsdk
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/go/*/bin/go
          test -f ~/.tipi/jdk/*/Contents/Home/bin/jar
          test -f ~/.tipi/nodejs/*/bin/node
          test -f ~/.tipi/openapi/*/openapi-generator-cli-5.1.1.jar
          test -f ~/.tipi/openapi-generator-script/*/openapi-generator-cli
          test -f ~/.tipi/platform/*/cmake/projects/Poco/hunter.cmake
          test -f ~/.tipi/python/*/bin/python
          test -f ~/.tipi/file-sync/*/pysearpc/client.py

  install-macos-light:
    name: install-macos-light
    runs-on: macos-latest
    steps:
      - name: test_install_on_macos
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"

          # Test install succeeeded 
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/file-sync/*/pysearpc/client.py

  install-linux-full:
    name: install-linux-full
    runs-on: ubuntu-latest
    steps:
      - name: test_install_on_linux
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          echo "Script source : ${script_source}"
          export TIPI_DISTRO_MODE=all
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
          
          # Test install succeeeded 
          echo "verif tipi"
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/clang/*/bin/clang
          test -f ~/.tipi/cmake/*/bin/cmake
          test -f ~/.tipi/emsdk/*/emsdk
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/go/*/bin/go
          test -f ~/.tipi/jdk/*/bin/jar
          test -f ~/.tipi/nodejs/*/bin/node
          test -f ~/.tipi/openapi/*/openapi-generator-cli-5.1.1.jar
          test -f ~/.tipi/openapi-generator-script/*/openapi-generator-cli
          test -f ~/.tipi/file-sync/*/pysearpc/client.py
          test -f ~/.tipi/platform/*/cmake/projects/Poco/hunter.cmake

  install-linux-light:
    name: install-linux-light
    runs-on: ubuntu-latest
    steps:
      - name: test_install_on_linux
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          echo "Script source : ${script_source}"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
          
          # Test install succeeeded 
          echo "verif tipi"
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/file-sync/*/pysearpc/client.py

  install-windows-powershell-full:
    name: install-windows-powershell-full
    runs-on: windows-latest
    steps:
      - name: test_install_on_windows_powershell
        run: |
          if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
            $script_source = $env:GITHUB_HEAD_REF.replace('refs/heads/', '')
          } else {
            $script_source = $env:GITHUB_REF.replace('refs/heads/', '')
          }
          $Env:TIPI_DISTRO_MODE="all"
          . { iwr -useb https://raw.githubusercontent.com/tipi-build/cli/$script_source/install/install_for_windows.ps1 } | iex 
          if (!($?)) {exit 1}
          # Test install succeeeded 
          if (!(Test-Path "C:\\ProgramData\\tipi\\tipi.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\clang\\*\\bin\\clang.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\cmake\\*\\bin\\cmake.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\emsdk\\*\\emsdk.bat" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\environments\\*\\xcode.cmake" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\go\\*\\bin\\go.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\jdk\\*\\bin\\jar.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\nodejs\\*\\node.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\openapi\\*\\openapi-generator-cli-5.1.1.jar" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\openapi-generator-script\\*\\openapi-generator-cli.bat" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\openssh\\*\\ssh.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\perl\\*\\README.txt" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\platform\\*\\cmake\\projects\\Poco\\hunter.cmake" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\python\\*\\python.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\file-sync\\*\\pysearpc\\client.py" -PathType leaf)) { exit 1; }
        shell: powershell

  install-windows-powershell-light:
    name: install-windows-powershell-light
    runs-on: windows-latest
    steps:
      - name: test_install_on_windows_powershell
        run: |
          if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
            $script_source = $env:GITHUB_HEAD_REF.replace('refs/heads/', '')
          } else {
            $script_source = $env:GITHUB_REF.replace('refs/heads/', '')
          }
          . { iwr -useb https://raw.githubusercontent.com/tipi-build/cli/$script_source/install/install_for_windows.ps1 } | iex 
          if (!($?)) {exit 1}
          # Test install succeeeded 
          if (!(Test-Path "C:\\ProgramData\\tipi\\tipi.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\environments\\*\\xcode.cmake" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\openssh\\*\\ssh.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.tipi\\file-sync\\*\\pysearpc\\client.py" -PathType leaf)) { exit 1; }
        shell: powershell  

  install-archlinux-full:
    name: install-archlinux-full
    runs-on: ubuntu-latest
    env:
      GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
      GITHUB_HEAD_REF: $GITHUB_HEAD_REF
      GITHUB_REF: $GITHUB_REF
    container: 
      image: archlinux
    steps:
      - name: test_install_on_linux
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          echo "Script source : ${script_source}"
          export TIPI_DISTRO_MODE=all
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
          # Test install succeeeded 
          echo "verif tipi"
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/clang/*/bin/clang
          test -f ~/.tipi/cmake/*/bin/cmake
          test -f ~/.tipi/emsdk/*/emsdk
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/go/*/bin/go
          test -f ~/.tipi/jdk/*/bin/jar
          test -f ~/.tipi/nodejs/*/bin/node
          test -f ~/.tipi/openapi/*/openapi-generator-cli-5.1.1.jar
          test -f ~/.tipi/openapi-generator-script/*/openapi-generator-cli
          test -f ~/.tipi/file-sync/*/pysearpc/client.py
          test -f ~/.tipi/platform/*/cmake/projects/Poco/hunter.cmake

  install-archlinux-light:
    name: install-archlinux-light
    runs-on: ubuntu-latest
    env:
      GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
      GITHUB_HEAD_REF: $GITHUB_HEAD_REF
      GITHUB_REF: $GITHUB_REF
    container: 
      image: archlinux
    steps:
      - name: test_install_on_linux
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          echo "Script source : ${script_source}"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
          # Test install succeeeded 
          echo "verif tipi"
          test -f /usr/local/bin/tipi
          test -f ~/.tipi/environments/*/xcode.cmake
          test -f ~/.tipi/file-sync/*/pysearpc/client.py

