name: check_install_script
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron : '0 0 * * *' # Every midnight check the released version of default branch
  

jobs:
  install-macos:
    name: install-macos
    runs-on: macos-latest
    steps:
      - name: test_install_on_macos
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"

          # Test install succeeeded 
          echo 1
          test -f /usr/local/bin/tipi
          echo 2
          test -f ~/.tipi/0b44dab/clang/bin/clang
          echo 3
          test -f ~/.tipi/0b44dab/cmake/bin/cmake
          echo 4
          test -f ~/.tipi/0b44dab/emsdk/emsdk
          echo 5
          test -f ~/.tipi/0b44dab/environments/xcode.cmake
          echo 6
          test -f ~/.tipi/0b44dab/go/bin/go
          echo 7
          test -f ~/.tipi/0b44dab/jdk/Contents/Home/bin/jar
          echo 8
          test -f ~/.tipi/0b44dab/nodejs/bin/node
          echo 9
          test -f ~/.tipi/0b44dab/openapi/openapi-generator-cli-5.1.1.jar
          echo 10
          test -f ~/.tipi/0b44dab/openapi-generator-script/openapi-generator-cli
          echo 11
          test -f ~/.tipi/0b44dab/plateform/jenkins.py
          echo 12
          test -f ~/.tipi/0b44dab/python/bin/python
          echo 13
          test -f ~/.tipi/0b44dab/file-sync/pysearpc/client.py


          

  install-linux:
    name: install-linux
    runs-on: ubuntu-latest
    steps:
      - name: test_install_on_linux
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          echo "Script source : ${script_source}"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
          
          # Test install succeeeded 
          echo 1
          test -f /usr/local/bin/tipi
          echo 2
          test -f ~/.tipi/0b44dab/clang/bin/clang
          echo 3
          test -f ~/.tipi/0b44dab/cmake/bin/cmake
          echo 4
          test -f ~/.tipi/0b44dab/emsdk/emsdk
          echo 5
          test -f ~/.tipi/0b44dab/environments/xcode.cmake
          echo 6
          test -f ~/.tipi/0b44dab/go/bin/go
          echo 7
          test -f ~/.tipi/0b44dab/jdk/bin/jar
          echo 8
          test -f ~/.tipi/0b44dab/nodejs/bin/node
          echo 9
          test -f ~/.tipi/0b44dab/openapi/openapi-generator-cli-5.1.1.jar
          echo 10
          test -f ~/.tipi/0b44dab/openapi-generator-script/openapi-generator-cli
          echo 11
          test -f ~/.tipi/0b44dab/plateform/jenkins.py
          echo 12
          test -f ~/.tipi/0b44dab/python/bin/python
          echo 13
          test -f ~/.tipi/0b44dab/file-sync/pysearpc/client.py




  install-windows-powershell:
    name: install-windows-powershell
    runs-on: windows-latest
    steps:
      - name: test_install_on_windows_powershell
        run: |
          if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
            $script_source = $env:GITHUB_HEAD_REF.replace('refs/heads/', '')
          } else {
            $script_source = $env:GITHUB_REF.replace('refs/heads/', '')
          }
          . { iwr -useb https://raw.githubusercontent.com/tipi-build/cli/$script_source/install/install_for_windows.ps1 } | iex 
          if (!($?)) {exit 1}
          # Test install succeeeded 
          echo 1
          if (!(Test-Path "C:\\ProgramData\\tipi\\tipi.exe" -PathType leaf)) { exit 1; }
          echo 2
          if (!(Test-Path "C:\\.tipi\\0b44dab\\clang\\bin\\clang.exe" -PathType leaf)) { exit 1; }
          echo 3
          if (!(Test-Path "C:\\.tipi\\0b44dab\\cmake\\bin\\cmake.exe" -PathType leaf)) { exit 1; }
          echo 4
          if (!(Test-Path "C:\\.tipi\\0b44dab\\emsdk\\emsdk.bat" -PathType leaf)) { exit 1; }
          echo 5
          if (!(Test-Path "C:\\.tipi\\0b44dab\\environments\\xcode.cmake" -PathType leaf)) { exit 1; }
          echo 6
          if (!(Test-Path "C:\\.tipi\\0b44dab\\go\\bin\\go.exe" -PathType leaf)) { exit 1; }
          echo 7
          if (!(Test-Path "C:\\.tipi\\0b44dab\\jdk\\bin\\jar.exe" -PathType leaf)) { exit 1; }
          echo 8
          if (!(Test-Path "C:\\.tipi\\0b44dab\\nodejs\\npm.bat" -PathType leaf)) { exit 1; }
          echo 9
          if (!(Test-Path "C:\\.tipi\\0b44dab\\openapi\\openapi-generator-cli-5.1.1.jar" -PathType leaf)) { exit 1; }
          echo 10 
          if (!(Test-Path "C:\\.tipi\\0b44dab\\openapi-generator-script\\openapi-generator-cli.bat" -PathType leaf)) { exit 1; }
          echo 11
          if (!(Test-Path "C:\\.tipi\\0b44dab\\openssh\\ssh.exe" -PathType leaf)) { exit 1; }
          echo 12
          if (!(Test-Path "C:\\.tipi\\0b44dab\\perl\\README.txt" -PathType leaf)) { exit 1; }
          echo 13
          if (!(Test-Path "C:\\.tipi\\0b44dab\\platform\\jenkins.py" -PathType leaf)) { exit 1; }
          echo 14
          if (!(Test-Path "C:\\.tipi\\0b44dab\\python\\python.exe" -PathType leaf)) { exit 1; }
          echo 15
          if (!(Test-Path "C:\\.tipi\\0b44dab\\file-sync\\pysearpc\\client.py" -PathType leaf)) { exit 1; }
        shell: powershell 

  install-archlinux:
    name: install-archlinux
    runs-on: ubuntu-latest
    env:
      GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
      GITHUB_HEAD_REF: $GITHUB_HEAD_REF
      GITHUB_REF: $GITHUB_REF
    container: 
      image: archlinux
    steps:
      - name: test_install_on_linux
        run: |
          if [ $GITHUB_EVENT_NAME = "pull_request" ]; then
            script_source=${GITHUB_HEAD_REF}
          else 
            script_source=${GITHUB_REF#refs/heads/}
          fi
          echo "Script source : ${script_source}"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tipi-build/cli/${script_source}/install/install_for_macos_linux.sh)"
          # Test install succeeeded 
          echo 1
          test -f /usr/local/bin/tipi
          echo 2
          test -f ~/.tipi/0b44dab/clang/bin/clang
          echo 3
          test -f ~/.tipi/0b44dab/cmake/bin/cmake
          echo 4
          test -f ~/.tipi/0b44dab/emsdk/emsdk
          echo 5
          test -f ~/.tipi/0b44dab/environments/xcode.cmake
          echo 6
          test -f ~/.tipi/0b44dab/go/bin/go
          echo 7
          test -f ~/.tipi/0b44dab/jdk/bin/jar
          echo 8
          test -f ~/.tipi/0b44dab/nodejs/bin/node
          echo 9
          test -f ~/.tipi/0b44dab/openapi/openapi-generator-cli-5.1.1.jar
          echo 10
          test -f ~/.tipi/0b44dab/openapi-generator-script/openapi-generator-cli
          echo 11
          test -f ~/.tipi/0b44dab/plateform/jenkins.py
          echo 12
          test -f ~/.tipi/0b44dab/python/bin/python
          echo 13
          test -f ~/.tipi/0b44dab/file-sync/pysearpc/client.py

